### ISSUE TITLE
no love for 👩🏽‍🦱👩🏻‍🦱👩🏼‍🦱👩🏾‍🦱👩🏿‍🦱?

### ISSUE THREAD

**Issue by auremoser** [wooorm/checkmoji#1]
Hello!

I love your tool, there is no support for curly girls. Please add it, thank you!

Expected behavior: results populate other versions of curly girls, like on emojipedia 

Current behavior: curly girl returns original emoji plus curly hair complement but then bugs up and you can’t add other emojis to the sentence

[
![ae203de5-84d0-41b7-ae1c-0a67b631837b](https://user-images.githubusercontent.com/1559703/50945168-58b57a80-1448-11e9-9192-547568ee8412.jpeg)
](url)

**Comment by wooorm** [comment]
Fixed! Thanks for reporting!! ❤️

<img width="657" alt="screenshot 2019-01-10 at 13 18 30" src="https://user-images.githubusercontent.com/944406/50969431-c318fa00-14de-11e9-8dc8-594c382ffa48.png">
