### ISSUE TITLE
Flags of countries on the Microsoft platform

### ISSUE THREAD

**Issue by debug45** [wooorm/checkmoji#2]
<img width="648" alt="Снимок экрана 2024-11-21 в 13 59 58" src="https://github.com/user-attachments/assets/4a4f5682-ba30-4cd7-81da-9468f5ec3f4c">

**Comment by wooorm** [comment]
Hi! Upstream is https://emojipedia.org/flag-vatican-city#designs; things can be requested there.
Also, I think everything’s broken when I checked a year or 2 ago or so, not sure this repo can be made to work again!
